### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by Ar4ikov** [kavishdahekar/IITG-Captcha-Solver-OpenCV-TensorFlow#5]
root@weetway:/var/www/html/csr/data_preparation# python3.5 segregate.py
/var/www/html/csr/data_collection/data/1474394385_skk4e.png
1474394385_skk4e.png
# debugging, i've trying to know more about lists
['s', 'k', 'k', '4', 'e']
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 ..., 
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
(519471.5091662556, array([[0],
       [0],
       [0],
       ..., 
       [4],
       [4],
       [4]], dtype=int32), array([[  35.6989975 ,  174.89631653],
       [  33.88435364,  122.27210999],
       [  33.54430389,  213.86709595],
       [  32.01204681,   78.50601959],
       [  38.28302002,   41.21509552]], dtype=float32))
[[   8.  181.]
 [   8.  182.]
 [   8.  183.]
 ..., 
 [  61.   44.]
 [  62.   42.]
 [  62.   43.]]
[array([255,   0,   0]), array([  0, 255,   0]), array([  0,   0, 255]), array([255, 255,   0]), array([255,   0, 255])]
# end of debugging
Traceback (most recent call last):
  File "segregate.py", line 110, in <module>
    thisColor = colors[labels[i]]
**TypeError: only integer scalar arrays can be converted to a scalar index**

**Comment by kavishdahekar** [comment]
thisColor = colors[labels[i]]
**TypeError: only integer scalar arrays can be converted to a scalar index**

**labels** list should contain integers since these are then used as an index for fetching the appropriate color from the **colors** list.

example:
```
>>> labels = [1,2,3,4,5]
>>> colors = ['red','blue','green','black','white']
>>> colors[labels[0]]
# output : 'blue'                  
```

This part is only for displaying the segmented characters in different colors. You can skip it if you want.

**Comment by Ar4ikov** [comment]
`print(labels)`
I've got: [[1] 
(lol)

`			try:
				thisColor = colors[labels[i]]
				imcpy[row][col] = thisColor
			except:
				pass
`
I mean, this code will fix my problem
